version: '3'
services:
  app:
    build: .
    container_name: user-service
    working_dir: /var/www/
    volumes:
      - ./www:/var/www/
    networks:
      - microservice_network

  webserver:
    image: nginx:alpine
    container_name: user-webserver
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
    networks:
      - microservice_network

  mysql:
    image: mysql
    container_name: user-mysql
    ports:
      - "3301:3306"
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql/my.cnf:/var/www/
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge
