version: '3'
services:
  loadbalance:
    build:
      context: .
      dockerfile: Dockerfile
    image: server_ubuntu
    container_name: lb
    ports:
      - 9000:80
      - 444:443
    volumes:
      - ./server_loadbalance/nginx/sites-available:/etc/nginx/sites-available
      - ./server_loadbalance/log:/var/log/nginx
      - ./server_loadbalance/ssl/:/etc/nginx/ssl
      #php.ini
    tty: true
    networks:
      - webserver_network

  # server ubuntu 1
  ubuntu1:
    image: server_ubuntu
    container_name: u1
    ports:
      - 9001:80
      - 6001:6001
    volumes:
      - ./html:/var/www/html
      - ./server_ubuntu1/log:/var/log/nginx
      - ./server_ubuntu1/php:/etc/php/
      - ./server_ubuntu1/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server_ubuntu1/nginx/sites-available:/etc/nginx/sites-available
    working_dir: /var/www/html
    tty: true
    networks:
      - webserver_network

  # server ubuntu 2
  ubuntu2:
    image: server_ubuntu
    container_name: u2
    ports:
      - 9002:80
    volumes:
      - ./html:/var/www/html
      - ./server_ubuntu2/log:/var/log/nginx
      - ./server_ubuntu2/php:/etc/php/
      - ./server_ubuntu2/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server_ubuntu2/nginx/sites-available:/etc/nginx/sites-available
    working_dir: /var/www/html
    tty: true
    networks:
      - webserver_network

  # database master
  mysql_master:
    image: mysql:5.7.44
    env_file:
      - ./db_master/mysql_master.env
    container_name: "mysql_master"
    command: --default-authentication-plugin=mysql_native_password
    restart: "no"
    ports:
      - 33306:3306
    volumes:
      - ./db_master/conf:/etc/mysql/conf.d
      - ./db_master/data:/var/lib/mysql
      - ./db_master/log/mysql:/var/log/mysql
      - ./db_sample/test_db-master:/opt/test_db-master
    networks:
      - webserver_network

  # database slave
  mysql_slave:
    image: mysql:5.7.44
    env_file:
      - ./db_slave/mysql_slave.env
    container_name: "mysql_slave"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33307:3306
    depends_on:
      - mysql_master
    volumes:
      - ./db_slave/conf:/etc/mysql/conf.d
      - ./db_slave/data:/var/lib/mysql
      - ./db_slave/log/mysql:/var/log/mysql
    networks:
      - webserver_network

  # database slave 2
  mysql_slave_2:
    image: mysql:5.7.44
    env_file:
      - ./db_slave_2/mysql_slave.env
    container_name: "mysql_slave_2"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33308:3306
    depends_on:
      - mysql_master
    volumes:
      - ./db_slave_2/conf:/etc/mysql/conf.d
      - ./db_slave_2/data:/var/lib/mysql
      - ./db_slave_2/log/mysql:/var/log/mysql
    networks:
      - webserver_network
  
  # redis
  redis:
    image: redis:7.2.3
    container_name: "server_redis"
    ports:
      - 6379:6379
    command: [
        "redis-server", 
        "--appendonly", 
        "no", 
        "--maxmemory", 
        "500mb", 
        "--maxmemory-policy", 
        "allkeys-lru",
        "--save",
        "60",
        "1000",
        "--loglevel",
        "warning",
      ]
    volumes: 
      - ./redis/data:/data
    networks:
      - webserver_network
      
networks:
  webserver_network:
    driver: bridge
