version: '3'
services:
  loadbalance:
    build:
      context: .
      dockerfile: Dockerfile
    image: server_ubuntu
    container_name: lb
    ports:
      - 9000:80
      - 443:443
    volumes:
      - ./server_loadbalance/nginx/sites-available:/etc/nginx/sites-available
      - ./server_loadbalance/log:/var/log/nginx
      - ./server_loadbalance/ssl/self-signed.conf:/etc/nginx/snippets/self-signed.conf
      #php.ini
    tty: true
    networks:
      - webserver_network

  # server ubuntu 1
  ubuntu1:
    image: server_ubuntu
    container_name: u1
    ports:
      - 9001:80
    volumes:
      - ./server_ubuntu1/nginx/sites-available:/etc/nginx/sites-available
      - ./server_ubuntu1/html:/var/www/html
      - ./server_ubuntu1/log:/var/log/nginx
      #php.ini
    tty: true
    networks:
      - webserver_network

  # server ubuntu 2
  ubuntu2:
    image: server_ubuntu
    container_name: u2
    ports:
      - 9002:80
    volumes:
      - ./server_ubuntu2/nginx/sites-available:/etc/nginx/sites-available
      - ./server_ubuntu2/html:/var/www/html
      - ./server_ubuntu2/log:/var/log/nginx
      #php.ini
    tty: true
    networks:
      - webserver_network

  # database master
  mysql_master:
    image: mysql:5.7
    env_file:
      - ./db_master/mysql_master.env
    container_name: "mysql_master"
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - ./db_master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_master/data:/var/lib/mysql
    networks:
      - webserver_network

  # database slave
  mysql_slave:
    image: mysql:5.7
    env_file:
      - ./db_slave/mysql_slave.env
    container_name: "mysql_slave"
    restart: "no"
    ports:
      - 5506:3306
    depends_on:
      - mysql_master
    volumes:
      - ./db_slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
      - ./db_slave/data:/var/lib/mysql
    networks:
      - webserver_network

networks:
  webserver_network:
    driver: bridge

