version: '3'
services:
  web:
    build: .
    container_name: chat-service
    working_dir: /var/www/
    volumes:
      - .:/var/www/
      - /var/www/node_modules
    ports:
      - "3000:3000"
    networks:
      - microservice_network

  mongo:
    image: mongo:7.0.3
    container_name: "chat-mongo"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo/data:/data/db
      - ./mongo/log:/var/log/mongodb
    networks:
      - microservice_network
      
  # http://localhost:8081/
  # admin:pass
  mongo-express:
    image: mongo-express
    container_name: "chat-mongo-express"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - microservice_network

networks:
  microservice_network:
    driver: bridge
